void drawScreenBlack();
void drawScreenWhite();
void drawScoreLine();
void drawGameLines(int startingXs[], int endingXs[], int numColumns);
void drawLabels();
void drawScore(int score);
void drawMenuScreenButtons(int curButtonSelected);
void drawMenuScreen(int curButtonSelected);
void drawPausedScreen(int curButtonSelected);
void drawPausedScreenButtons(int curButtonSelected);
void drawGameOverScreen(int curButtonSelected);
void drawGameOverScreenButtons(int curButtonSelected);
void drawDifficultyScreen(int curButtonSelected);
void drawDifficultyScreenButtons(int curButtonSelected);
void drawSongSelectionScreen(int curButtonSelected);
void drawSongSelectionScreenButtons(int curButtonSelected);